sudo: required

language: c++

addons:
  apt:
    sources: &sources
    - ubuntu-toolchain-r-test

    packages:
    - libeigen3-dev
    - g++-5
    - gcc-5
    - g++-6
    - gcc-6

env:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true
  
matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    # LINUX
    # GCC 5
    - os: linux
      env: COMPILER=g++-5 CCOMPILER=gcc-5 COMPUTE_COVERAGE=false
      compiler: gcc

    # GCC 6
    - os: linux
      env: COMPILER=g++-6 CCOMPILER=gcc-6 GCOV=gcov-6 COMPUTE_COVERAGE=true MAKE_DOC=true
      compiler: gcc

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR} && mkdir deps && cd deps
  
  ############################################################################
  # Override compiler if needed
  ############################################################################
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; export CC=${CCOMPILER}; fi

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}
    
  ############################################################################
  # Install gtest
  ############################################################################
  - git clone https://github.com/google/googletest.git
  - cd googletest && mkdir build && cd build 
  - cmake -DCMAKE_CXX_FLAGS="-std=c++11" .. && sudo make && sudo make install

  ############################################################################
  # Install FunG
  ############################################################################
  - cd ${DEPS}
  - git clone https://github.com/lubkoll/FunG.git
  - sudo cp -r FunG/fung /usr/local/include

  ############################################################################
  # Install Eigen
  ############################################################################

  - cd ${DEPS}
  - git clone https://github.com/eigenteam/eigen-git-mirror.git
  - cd eigen-git-mirror && mkdir build && cd build && cmake .. && sudo make install

  ############################################################################
  # Install Spacy
  ############################################################################
  - cd ${DEPS}
  - git clone https://github.com/spacy-dev/Spacy.git
  - cd Spacy && mkdir build && cd build && cmake .. && make -j2 && sudo make install

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake .. -DEigen=ON
  - make -j2 && ctest

