sudo: required

language: c++

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  
  ############################################################################
  # Install gtest
  ############################################################################
  - git clone https://github.com/google/googletest.git
  - cd googletest && mkdir build && cd build && cmake .. && make -j2
  - sudo cp -r ../googletest/include/gtest /usr/local/include/
  - sudo cp googlemock/gtest/lib*.a /usr/local/lib

  ############################################################################
  # Install FunG
  ############################################################################
  - cd ${DEPS}
  - git clone https://github.com/lubkoll/FunG.git
  - sudo cp -r FunG/fung /usr/local/include

  ############################################################################
  # Install Spacy
  ############################################################################
  - cd ${DEPS}
  - git clone https://github.com/spacy-dev/Spacy.git
  - cd Spacy && mkdir build && cd build && cmake .. && make -j2 && sudo make install

  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake .. -DEigen=ON
  - make -j2 && ctest

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake .. -DEigen=ON
  - make -j2 && ctest

