sudo: required

language: c++

addons:
  apt:
    sources: &sources
    - ubuntu-toolchain-r-test

    packages:
    - libboost-dev
    - g++-5
    - gcc-5
    - g++-6
    - gcc-6

env:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true
  
matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    # LINUX
    # GCC 5
    - os: linux
      env: COMPILER=g++-5 CCOMPILER=gcc-5 COMPUTE_COVERAGE=false
      compiler: gcc

    # GCC 6
    - os: linux
      env: COMPILER=g++-6 CCOMPILER=gcc-6 GCOV=gcov-6 COMPUTE_COVERAGE=true MAKE_DOC=true
      compiler: gcc

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR} && mkdir deps && cd deps
  
  ############################################################################
  # Override compiler if needed
  ############################################################################
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; export CC=${CCOMPILER}; fi

  ############################################################################
  # Install cmake
  ############################################################################
  - |
    sudo apt purge cmake
    cd $DEPS
    wget http://github.com/Kitware/CMake/releases/download/v3.13.1/cmake-3.13.1.tar.gz
    tar xzf cmake-3.13.1.tar.gz && cd cmake-3.13.1
    ./bootstrap && make && sudo make install
    
  ############################################################################
  # Install gtest
  ############################################################################
  - git clone https://github.com/google/googletest.git
  - cd googletest && mkdir build && cd build 
  - cmake -DCMAKE_CXX_FLAGS="-std=c++11" .. && sudo make && sudo make install

  ############################################################################
  # Install FunG
  ############################################################################
  - cd ${DEPS}
  - git clone https://github.com/lubkoll/FunG.git
  - cd FunG && mkdir build && cd build
  - cmake .. && sudo cmake --build . --target install

  ############################################################################
  # Install Eigen
  ############################################################################

  - cd ${DEPS}
  - git clone https://github.com/eigenteam/eigen-git-mirror.git
  - cd eigen-git-mirror && mkdir build && cd build && cmake .. && sudo make install

  ############################################################################
  # Install Spacy
  ############################################################################
  - cd ${DEPS}
  - git clone https://github.com/spacy-dev/Spacy.git
  - cd Spacy && mkdir build && cd build && cmake .. && make -j2 && sudo make install

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake .. -DEigen=ON
  - make -j2 && ctest

